# Generated by Django 5.2.1 on 2025-05-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guru', 'Guru'), ('none', 'None'), ('siswa', 'Siswa')], default='none', max_length=10),
        ),
    ]
