# Generated by Django 5.2.1 on 2025-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guru', 'Guru'), ('siswa', 'Siswa'), ('none', 'None')], default='none', max_length=10),
        ),
    ]
