# Generated by Django 5.2.1 on 2025-05-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nis', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=10)),
            ],
        ),
    ]
