# Generated by Django 5.2.1 on 2025-05-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('nip', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
